
[[redirects]]
  from = "/industrylaw/index.html"
  to = "/legal-industry"


[[redirects]]
  from = "/industrylaw"
  to = "/legal-industry"

  
[[redirects]]
  from = "/industrymedical/index.html"
  to = "/medical-industry"


[[redirects]]
  from = "/industrymedical"
  to = "/medical-industry"

[[redirects]]
  from = "/industrytechnical/index.html"
  to = "/technical-industry"


[[redirects]]
  from = "/industrytechnical"
  to = "/technical-industry"

[[redirects]]
  from = "https://englisharabictranslations.com/industryfinance/index.html"
  to = "https://englisharabictranslations.com/finance-industry"


[[redirects]]
  from = "https://englisharabictranslations.com/industryfinance"
  to = "https://englisharabictranslations.com/finance-industry"


[[redirects]]
  from = "/industryit/index.html"
  to = "/software-industry"


[[redirects]]
  from = "/industryit"
  to = "/software-industry"


[[redirects]]
  from = "/industrymarketing/index.html"
  to = "/marketing-industry"


[[redirects]]
  from = "/industrymarketing"
  to = "/marketing-industry"
